### ISSUE TITLE
Expression pedal

### ISSUE THREAD

**Issue by psweetie** [Morningstar-Engineering/MC8-MIDI-Controller#21]
I have a trs cable from one of the omni ports to a jack and the Omni pretty is setup as an expression pedal. When i plug in and expression pedal i have programmed it to do either volume or effect depending on another prest and that all works fine. The issue is when the legal is NIT plugged in, the mc8 seems to slow and some buttons become unresponsive. Last time i checked mc8 seemed to be sending endless cc messages. Would ideally like to recognise when an exp pedal is at the end of the connection such that it could stop anything but intended messages?

**Comment by tyzjames** [comment]
The issue is because a TRS cable is connected to the Omniport, but the other end is left floating - so the controller is reading the voltage jumps (because the cable is not connected to any expression) and reading them as an expression pedal being moved. If you plug the cable out from the Omniport then it will be fine.

Anyway, I have uploaded a firmware dated 2021-10-30 that might solve this issue for you - let me know.

**Comment by psweetie** [comment]
That seems to solve the freeze problem I had, def difficult to unplug cable from MC8 on the pedalboard so this is good. Thanks James.

Regards
Philip

***@***.******@***.***>

**Comment by psweetie** [comment]
THe new firmware certainly stops the freezing I was getting. Closed
